### PR TITLE
add missing become for Ubuntu

### PR DESCRIPTION
**Pull request by JonnyJD**
I tried to setup Omero with Ansible running @role: ome.omero_web@
on an Ubuntu 18 LTS VM.
This depends on @ome.nginx@ (not sure yet if I will keep this or not though)
and running as a non-privileged ansible_user ("ansible", has sudo permission)
I get:

```
TASK [ome.nginx : system packages | setup nginx ppa repo] *************************************************
fatal: [local-omero18]: FAILED! => {
    "changed": false,
    "cmd": "apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 8B3981E7A6852F782CC4951600A6F0A3C300EE8C",
    "rc": 1
}

STDOUT:

Executing: /tmp/apt-key-gpghome.7r2GeM6CVP/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 8B3981E7A6852F782CC4951600A6F0A3C300EE8C


STDERR:

Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key
gpg: key 00A6F0A3C300EE8C: public key "Launchpad Stable" imported
gpg: Total number processed: 1
gpg:               imported: 1
/usr/bin/apt-key: 334: /usr/bin/apt-key: cannot create /etc/apt/trusted.gpg: Permission denied
cat: /tmp/apt-key-gpghome.7r2GeM6CVP/gpgoutput.log: No such file or directory


MSG:

Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: key 00A6F0A3C300EE8C: 1 signature not checked due to a missing key
gpg: key 00A6F0A3C300EE8C: public key "Launchpad Stable" imported
gpg: Total number processed: 1
gpg:               imported: 1
/usr/bin/apt-key: 334: /usr/bin/apt-key: cannot create /etc/apt/trusted.gpg: Permission denied
cat: /tmp/apt-key-gpghome.7r2GeM6CVP/gpgoutput.log: No such file or directory
```

This PR should fix that.

### CODE REVIEW

**Comment by JonnyJD** [comment]
The failing test does not seem to be related:
```
    E           AssertionError: assert False
    E            +  where False = <built-in method startswith of str object at 0x7fafd40e0d98>('nginx version: nginx/1.16.')
    E            +    where <built-in method startswith of str object at 0x7fafd40e0d98> = 'nginx version: nginx/1.18.0 (Ubuntu)'.startswith
```

**Review by manics — APPROVED** [review]
Thanks!

The failing test should be fixed by https://github.com/ome/ansible-role-nginx/pull/7

**Comment by JonnyJD** [comment]
I merged master for the test fix.

**Review by manics — APPROVED** [review]

**Comment by sbesson** [comment]
Version `2.0.2` of the role with this change was deployed to Galaxy by manually reimporting the role until we roll out some automation of the deployment via GitHub actions.

Thanks @JonnyJD

**Pull request merged**
